/**
 * TOML scenario format for steering bpmn-js-token-simulation.
 *
 * By itself, token simulation only knows how to auto-advance through
 * activities — a gateway with multiple outgoing flows or a catch event
 * needs an explicit decision (in the interactive tool, a mouse click).
 * A scenario is the headless equivalent of that click stream: an ordered
 * list of triggers, each either firing an event (start/intermediate-catch/
 * boundary) or steering a gateway (which outgoing flow(s) to take).
 *
 * `exportScenarioTemplate` inspects a diagram and generates a ready-to-run
 * scenario covering every decision point it finds, so scenario authoring
 * starts from "this diagram's actual gateways/events" rather than a blank
 * file.
 */

import { BpmnModdle } from 'bpmn-moddle';
import camundaModdle from 'camunda-bpmn-moddle/resources/camunda.json';
import { parse as parseToml } from 'smol-toml';

/** One scenario step: fire an event, or steer a gateway. */
export interface ScenarioTrigger {
  /** BPMN element id (start event, catch/boundary event, or gateway). */
  element: string;
  /**
   * Virtual time (ms from simulation start) at which this trigger becomes
   * due. Applied as soon as the clock reaches this time *and*, for events,
   * the element is actually waiting to be triggered. Default: 0.
   */
  at_ms?: number;
  /**
   * Gateway steering only: the outgoing sequence flow id to take (exclusive
   * gateway), or ids to take (inclusive gateway fork). Omit for event
   * triggers (start/intermediate-catch/boundary).
   */
  take?: string | string[];
}

export interface Scenario {
  /** Rendered animation frame rate. Default: 12. */
  fps?: number;
  trigger?: ScenarioTrigger[];
}

/** Parse a scenario TOML document. */
export function parseScenario(toml: string): Scenario {
  const parsed = parseToml(toml) as unknown as Scenario;

  for (const trigger of parsed.trigger ?? []) {
    if (!trigger.element || typeof trigger.element !== 'string') {
      throw new Error('[bpmn-to-image] scenario trigger is missing a string "element" id');
    }
  }

  return parsed;
}

// ── Scaffold export ─────────────────────────────────────────────────────

const GATEWAY_TYPES = new Set(['bpmn:ExclusiveGateway', 'bpmn:InclusiveGateway']);
const CATCH_EVENT_TYPES = new Set(['bpmn:StartEvent', 'bpmn:IntermediateCatchEvent']);

interface DiscoveredTrigger {
  element: string;
  name?: string;
  comment?: string;
  take?: string;
  takeOptions?: string[];
}

function isSequenceFlow(el: any): boolean {
  return el?.$type === 'bpmn:SequenceFlow';
}

/** Recursively walk flowElements (into sub-processes) collecting decision points, in document order. */
function collectTriggers(flowElements: any[] | undefined, triggers: DiscoveredTrigger[]): void {
  for (const el of flowElements ?? []) {
    if (GATEWAY_TYPES.has(el.$type)) {
      const outgoing = (el.outgoing ?? []).filter(isSequenceFlow);
      if (outgoing.length > 1) {
        triggers.push({
          element: el.id,
          name: el.name,
          take: outgoing[0].id,
          takeOptions: outgoing.map((f: any) => f.id),
        });
      }
    } else if (CATCH_EVENT_TYPES.has(el.$type)) {
      triggers.push({ element: el.id, name: el.name });
    }

    if (Array.isArray(el.flowElements)) {
      collectTriggers(el.flowElements, triggers);
    }
  }

  // Boundary events are attached to activities, not listed as separate
  // "incoming" flow — they still appear directly in flowElements, so a
  // second pass just for boundary events would be redundant; catch it here.
  for (const el of flowElements ?? []) {
    if (el.$type === 'bpmn:BoundaryEvent') {
      triggers.push({ element: el.id, name: el.name, comment: 'boundary event' });
    }
  }
}

/**
 * Inspect a BPMN diagram and generate a scenario TOML scaffold covering
 * every gateway (with >1 outgoing flow) and start/intermediate-catch/
 * boundary event, in diagram document order. Gateways default to their
 * first outgoing flow (matching bpmn-js-token-simulation's own interactive
 * default) with the alternatives listed in a comment; events are spaced out
 * by 500ms so the exported scenario renders a sensible animation as-is.
 */
export async function exportScenarioTemplate(xml: string): Promise<string> {
  const moddle = new BpmnModdle({ camunda: camundaModdle });
  const { rootElement } = await moddle.fromXML(xml);

  const processes = (rootElement.rootElements ?? []).filter(
    (el: any) => el.$type === 'bpmn:Process'
  );

  const discovered: DiscoveredTrigger[] = [];
  for (const process of processes) {
    collectTriggers(process.flowElements, discovered);
  }

  const lines: string[] = [
    '# Token-simulation scenario, generated by bpmn-to-image.',
    '#',
    '# Each [[trigger]] fires a start/catch/boundary event, or steers a',
    '# gateway via `take`. Reorder or edit `at_ms` (ms from simulation',
    '# start) to control pacing; delete entries you do not need.',
    '',
    'fps = 12',
    '',
  ];

  let atMs = 0;
  for (const trigger of discovered) {
    const label = trigger.name
      ? ` # ${trigger.name}`
      : trigger.comment
        ? ` # ${trigger.comment}`
        : '';
    lines.push('[[trigger]]');
    lines.push(`element = "${trigger.element}"${label}`);
    lines.push(`at_ms = ${atMs}`);
    if (trigger.take) {
      lines.push(`take = "${trigger.take}"  # options: ${trigger.takeOptions!.join(', ')}`);
    }
    lines.push('');
    atMs += 500;
  }

  return lines.join('\n');
}
